### PR TITLE
README.md: added direct links to latest builds

### PR DESCRIPTION
**Pull request by ApfelUser**

### CODE REVIEW

**Comment by thinkofdeath** [comment]
Could you change the commit message to 
`README.md: added direct links to latest builds`
and for 32bit linux and osx link to the issues instead of leaving them blank

**Comment by Szperak** [comment]
Commit message...
Use git command

**Comment by ApfelUser** [comment]
I used the Web-Editor as you can see (`patch-1` -.-), sorry. Let me clone the repo.

**Comment by thinkofdeath** [comment]
Pulled manually, thanks

**Pull request closed without merging**
